# site properties and page defaults
title: Trevon's research lab
subtitle: 
description: Nanophotonics and metamaterials research at Korea University Sejong Campus
header: images/wave_footer_image.jpeg
footer: images/wave_footer_image.jpeg
proofer: false


# site social media and other links
links:
  email: trevon@korea.ac.kr
  orcid: 0000-0001-9458-6062
  google-scholar: aVP_G7oAAAAJ
  github: 
  twitter: 
  youtube: 

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_team
  - scope:
      type: "team"
    values:
      layout: team
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each team member
  team:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
