- role: Early Career Editor
  journals:
  - Advanced Photonics
  - Progress in Electromagnetics Research (PIER)

- role: Guest Editor
  journals:
  - Nanophotonics

- role: Peer Reviewer
  journals:
  - "Light: Science & Applications"
  - Advanced Materials
  - Nature Communications
  - Photonix
  - Laser & Photonics Reviews
  - Advanced Science
  - ACS Photonics
  - Progress in Electromagnetics Research (PIER)
  - Chemical Science
  - Materials Today Electronics
  - Advanced Composites and Hybrid Materials
  - Optics and Laser Technology
  - Advanced Theory and Simulations
  - Applied Thermal Engineering
  - Results in Materials
  - Optical Materials Express
  - npj Nanophotonics
  - Optics Express
  - Nanophotonics
  - Scientific Reports
  - Optics Letters
  - Results in Physics
  - Optics & Lasers in Engineering
  - Applied Optics
  - APL Photonics
  - Advanced Physics Research
  - Photonics Research
  - Advanced Photonics Nexus
  - JOSA B
  - Discover Nano