- role: Guest Editor
  journals:
  - Nanophotonics

- role: Peer Reviewer
  journals:
  - "Light: Science & Applications"
  - Nature Communications
  - Photonix
  - Laser & Photonics Reviews
  - ACS Photonics
  - Materials Today Electronics
  - Advanced Composites and Hybrid Materials
  - Optics and Laser Technology
  - Advanced Theory and Simulations
  - Applied Thermal Engineering
  - Results in Materials
  - Optical Materials Express
  - npj Nanophotonics
  - Optics Express
  - Nanophotonics
  - Scientific Reports
  - Optics Letters
  - Results in Physics
  - Optics & Lasers in Engineering
  - Applied Optics
  - APL Photonics
  - Photonics Research
  - Advanced Photonics Nexus
  - JOSA B
