- role: Guest Editor
  journals:
  - Nanophotonics

- role: Peer Reviewer
  journals:
  - "Light: Science & Applications"
  - Nature Communications
  - Optical Materials Express
  - npj Nanophotonics
  - Optics Express
  - Nanophotonics
  - Scientific Reports
  - Optics Letters
  - Results in Physics
  - Optics & Lasers in Engineering
  - Applied Optics
  - APL Photonics
  - Photonics Research
  - Advanced Photonics Nexus
  - JOSA B
